/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServidorDeChat.Telas;

import ServidorDeChat.RN.ClientesRN;
import ServidorDeChat.VO.ClientesVO;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.ArrayList;

/**
 *
 * @author lennonalves
 */
public class Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Servidor
     */
    
    public static Servidor instancia;
    
    protected Servidor() {
        initComponents();
    }
    
    public static Servidor getInstancia() {
        if (instancia == null)
            instancia = new Servidor();
        return instancia;
    }
    
    boolean flag = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnLigar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setText("Porta:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 50, 16);

        btnLigar.setText("LIGAR");
        btnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigar);
        btnLigar.setBounds(20, 110, 360, 40);

        jLabel3.setText("Clientes conectados:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 150, 16);

        txtPorta.setText("1970");
        txtPorta.setToolTipText("");
        txtPorta.setEnabled(false);
        getContentPane().add(txtPorta);
        txtPorta.setBounds(70, 70, 310, 28);

        jLabel4.setFont(new java.awt.Font("PakType Naqsh", 0, 24)); // NOI18N
        jLabel4.setText("Conexão do Servidor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 20, 210, 30);

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IP", "Porta", "Nome"
            }
        ));
        jScrollPane1.setViewportView(tbClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 360, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarActionPerformed
        // TODO add your handling code here:
        
        ClientesVO cvo = ClientesVO.getInstancia();
        ClientesRN crn = ClientesRN.getInstancia();
        
        crn.zerarClientes(cvo);
        
        if(flag == false)
        {
            btnLigar.setText("DESLIGAR");
            flag = true;
            
            System.out.println("Status: Servidor Ativo");
            
            try {
                
                DatagramSocket s = new DatagramSocket(Integer.parseInt(txtPorta.getText()));

                while(true) {
                    
                    byte[] buffer = new byte[256];
                    DatagramPacket request = new DatagramPacket(buffer, buffer.length);
                    s.receive(request);

                    String m = new String(request.getData());
                    InetAddress endereco = request.getAddress();
                    
                    cvo.setHostId(null); cvo.setHostName(null); cvo.setHostAddress(null);
                    
                    if (m.substring(0, 1).equals("1")) 
                    {
                        
                        cvo.setHostId(m.substring(0, 2).trim());
                        cvo.setHostName(m.substring(2).trim());
                        cvo.setHostAddress(endereco.getHostAddress());
                        cvo.setHostPort(Integer.toString(request.getPort()));
                        System.out.print(crn.adicionaCliente(cvo));
                            
                    }
                    
                    if (m.substring(0, 1).equals("5")) 
                    { 
                        
                        cvo.setHostId(m.substring(0, 2).trim());
                        cvo.setHostName(m.substring(2).trim());
                        cvo.setHostAddress(endereco.getHostAddress());
                        cvo.setHostPort(Integer.toString(request.getPort()));
                        System.out.println(crn.removeCliente(cvo));
                    }
                    
                }
            }
            catch (IOException e) 
            {
                System.out.println("Status: Servidor Desligado");
                System.out.println("IOException: " + e);
            }
        }
        else
        {
            btnLigar.setText("LIGAR");
            flag = false;
        }
    }//GEN-LAST:event_btnLigarActionPerformed
    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void atualizarListaCliente(){   
        
        ClientesVO cvo = ClientesVO.getInstancia();
        ClientesRN crn = ClientesRN.getInstancia();
        crn.atualizaClientes(cvo);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLigar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTbClientes() {
        return tbClientes;
    }

    public void setTbClientes(javax.swing.JTable tbClientes) {
        this.tbClientes = tbClientes;
    }
}
