/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tarefas.Decorator;

/**
 *
 * @author lennonalves
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form Decorator
     */
    public TelaCliente() {
        initComponents();
    }
    
    private Janela j;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbFerramentas = new javax.swing.JRadioButton();
        rbBorda = new javax.swing.JRadioButton();
        rbMenu = new javax.swing.JRadioButton();
        rbStatus = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        btnGerar.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        btnGerar.setText("GERAR");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerar);
        btnGerar.setBounds(30, 150, 320, 90);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("Selecionar o estilo de janela:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 210, 16);

        rbFerramentas.setText("Janela Ferramentas");
        rbFerramentas.setToolTipText("");
        getContentPane().add(rbFerramentas);
        rbFerramentas.setBounds(30, 60, 150, 23);

        rbBorda.setText("Janela Borda");
        getContentPane().add(rbBorda);
        rbBorda.setBounds(30, 100, 150, 23);

        rbMenu.setText("Janela Menu");
        rbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMenuActionPerformed(evt);
            }
        });
        getContentPane().add(rbMenu);
        rbMenu.setBounds(200, 60, 150, 23);

        rbStatus.setText("Janela Status");
        getContentPane().add(rbStatus);
        rbStatus.setBounds(200, 100, 150, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here:
        if(rbFerramentas.isSelected() == true)
            System.out.println("Funcionou");
        j = new JanelaBarraFerramenta(j);
        j.adicionaComponente();
        j.getFrame().setVisible(true);
    }//GEN-LAST:event_btnGerarActionPerformed

    private void rbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbBorda;
    private javax.swing.JRadioButton rbFerramentas;
    private javax.swing.JRadioButton rbMenu;
    private javax.swing.JRadioButton rbStatus;
    // End of variables declaration//GEN-END:variables
}
