/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TELAS;

import RN.AvaliadorRN;
import VO.AvaliadorVO;
import javax.swing.JOptionPane;

/**
 *
 * @author lennon
 */
public class TelaAvaliador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAvaliador
     */
    
    private int idUser = 0;
    public static TelaAvaliador instancia;
    
    protected TelaAvaliador() {
        initComponents();
    }
    
    public static TelaAvaliador getInstancia() {
        if (instancia == null)
            instancia = new TelaAvaliador();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgAtualizar = new javax.swing.JLabel();
        lblAtualizar = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        lbl03 = new javax.swing.JLabel();
        lblTituloArtigo = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lblTituloTela = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lblNomeAvaliador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAvaliacao = new javax.swing.JTextArea();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IFIP Congressos //Sistema de Avaliação de Artigos");
        setMinimumSize(new java.awt.Dimension(663, 399));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        imgAtualizar.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        imgAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        imgAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/atualizar32.png"))); // NOI18N
        imgAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAtualizarMouseClicked(evt);
            }
        });
        getContentPane().add(imgAtualizar);
        imgAtualizar.setBounds(570, 10, 40, 40);

        lblAtualizar.setFont(new java.awt.Font("Eras Medium ITC", 0, 10)); // NOI18N
        lblAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblAtualizar.setText("Atualizar");
        lblAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtualizarMouseClicked(evt);
            }
        });
        getContentPane().add(lblAtualizar);
        lblAtualizar.setBounds(570, 40, 50, 13);

        btnVisualizar.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnVisualizar.setText("VISUALIZAR ARTIGO");
        btnVisualizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisualizar);
        btnVisualizar.setBounds(270, 310, 150, 30);

        btnEnviar.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnEnviar.setText("ENVIAR AVALIAÇÃO");
        btnEnviar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(440, 310, 180, 30);

        lbl03.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lbl03.setForeground(new java.awt.Color(255, 255, 255));
        lbl03.setText("Avaliação do Artigo:");
        getContentPane().add(lbl03);
        lbl03.setBounds(20, 100, 150, 17);

        lblTituloArtigo.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        lblTituloArtigo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloArtigo.setText("Nome");
        getContentPane().add(lblTituloArtigo);
        lblTituloArtigo.setBounds(150, 70, 470, 17);

        lbl02.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lbl02.setForeground(new java.awt.Color(255, 255, 255));
        lbl02.setText("Título do Artigo:");
        getContentPane().add(lbl02);
        lbl02.setBounds(20, 70, 120, 17);

        lblTituloTela.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblTituloTela.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTela.setText("Sistema de Avaliação de Artigos");
        getContentPane().add(lblTituloTela);
        lblTituloTela.setBounds(20, 10, 530, 29);

        lbl01.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lbl01.setForeground(new java.awt.Color(255, 255, 255));
        lbl01.setText("Olá,");
        getContentPane().add(lbl01);
        lbl01.setBounds(20, 50, 30, 15);

        lblNomeAvaliador.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        lblNomeAvaliador.setForeground(new java.awt.Color(255, 102, 0));
        lblNomeAvaliador.setText("Nome");
        getContentPane().add(lblNomeAvaliador);
        lblNomeAvaliador.setBounds(50, 50, 570, 15);

        txtAvaliacao.setColumns(20);
        txtAvaliacao.setRows(5);
        jScrollPane1.setViewportView(txtAvaliacao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 600, 160);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/fundo.jpg"))); // NOI18N
        imgFundo.setName("imgFundo"); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(-10, -10, 680, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void limparDados() {
        txtAvaliacao.setText("");
    }
    
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        
        AvaliadorVO avo = AvaliadorVO.getInstancia();
        avo.setTituloArtigo(lblNomeAvaliador.getText());
        avo.setTituloArtigo(lblTituloArtigo.getText());
        avo.setAvaliacaoArtigo(txtAvaliacao.getText());
        
        AvaliadorRN arn = AvaliadorRN.getInstancia();
        JOptionPane.showMessageDialog(null, arn.avaliaArtigo(avo));
        
        limparDados();
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    void atualizarCampos(){
        
        AvaliadorVO avo = AvaliadorVO.getInstancia();
        AvaliadorRN arn = AvaliadorRN.getInstancia();
        String mensagem = arn.atualizarCampos(avo);
        
        lblNomeAvaliador.setText(avo.getNomeAvaliador());
        lblTituloArtigo.setText(avo.getTituloArtigo());
        txtAvaliacao.setText("");
        
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        atualizarCampos();
    }//GEN-LAST:event_formWindowActivated

    private void imgAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAtualizarMouseClicked
        // TODO add your handling code here:
        atualizarCampos();
    }//GEN-LAST:event_imgAtualizarMouseClicked

    private void lblAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtualizarMouseClicked
        // TODO add your handling code here:
        atualizarCampos();
    }//GEN-LAST:event_lblAtualizarMouseClicked

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSubmeterArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSubmeterArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSubmeterArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSubmeterArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAvaliador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel imgAtualizar;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lblAtualizar;
    private javax.swing.JLabel lblNomeAvaliador;
    private javax.swing.JLabel lblTituloArtigo;
    private javax.swing.JLabel lblTituloTela;
    private javax.swing.JTextArea txtAvaliacao;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the idUser
     */
    public int getIdUser() {
        return idUser;
    }

    /**
     * @param idUser the idUser to set
     */
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
}
