/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServidorDeChat;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.Socket;

/**
 *
 * @author lennonalves
 */
public class Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Servidor
     */
    
    public static Servidor instancia;
    
    protected Servidor() {
        initComponents();
    }
    
    public static Servidor getInstancia() {
        if (instancia == null)
            instancia = new Servidor();
        return instancia;
    }
    
    boolean flag = false;
    int cont = 1;
    
    String imprime, hostId, hostName, hostAddress;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClientes = new javax.swing.JTextArea();
        btnLigar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setText("Porta:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 50, 16);

        txtClientes.setColumns(20);
        txtClientes.setRows(5);
        txtClientes.setEnabled(false);
        jScrollPane1.setViewportView(txtClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 360, 150);

        btnLigar.setText("LIGAR");
        btnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLigar);
        btnLigar.setBounds(20, 110, 360, 40);

        jLabel3.setText("Clientes conectados:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 150, 16);

        txtPorta.setText("1970");
        txtPorta.setToolTipText("");
        txtPorta.setEnabled(false);
        getContentPane().add(txtPorta);
        txtPorta.setBounds(70, 70, 310, 28);

        jLabel4.setFont(new java.awt.Font("PakType Naqsh", 0, 24)); // NOI18N
        jLabel4.setText("Conexão do Servidor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 20, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigarActionPerformed
        // TODO add your handling code here:
        if(flag == false)
        {
            btnLigar.setText("DESLIGAR");
            flag = true;
            
            System.out.println("Status: Servidor Ativo");
            
            try {
                DatagramSocket s = new DatagramSocket(Integer.parseInt(txtPorta.getText()));

                while(true) {
                    byte[] buffer = new byte[256];
                    DatagramPacket request = new DatagramPacket(buffer, buffer.length);
                    s.receive(request);

                    String m = new String(request.getData());

                    InetAddress endereco = request.getAddress();

                    hostId = null; hostName = null; hostAddress = null;

                    hostId = m.substring(0, 2).trim();
                    hostName = m.substring(2).trim();
                    hostAddress = endereco.getHostAddress();

                    System.out.println(hostId + hostName + hostAddress);
                    imprime = imprime + hostId + hostName + hostAddress;
                }
            }
            catch (IOException e) 
            {
                System.out.println("Status: Servidor Desligado");
                System.out.println("IOException: " + e);
            }
        }
        else
        {
            btnLigar.setText("LIGAR");
            flag = false;
        }
    }//GEN-LAST:event_btnLigarActionPerformed

    private void atualizarListaClientes(){
        
    }
    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        atualizarListaClientes();
    }//GEN-LAST:event_formWindowGainedFocus

    private void atualizarListaCliente(){
        txtClientes.setText(imprime);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLigar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtClientes;
    private javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables
}
