/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VISAO;

import PRINCIPAL.Conexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lennon
 */
public class TelaControleFinanceiro extends javax.swing.JFrame {

    /**
     * Creates new form ControleFinanceiro
     */
    
    DefaultTableModel dtm = new DefaultTableModel();
    public static TelaControleFinanceiro instancia;
    
    protected TelaControleFinanceiro() {
        initComponents();
        dtm = (DefaultTableModel) tbGastos.getModel();
    }
    
    public static TelaControleFinanceiro getInstancia() {
        if (instancia == null)
            instancia = new TelaControleFinanceiro();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricaoItem = new javax.swing.JTextArea();
        lblDescricaoItem = new javax.swing.JLabel();
        lblCustoItem = new javax.swing.JLabel();
        txtCustoItem = new javax.swing.JTextField();
        lblAtualizar = new javax.swing.JLabel();
        imgAtualizar = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblLucro = new javax.swing.JLabel();
        lblQtdLucro = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        lblQtdSaida = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        lblQtdEntrada = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblPatrocinadores = new javax.swing.JLabel();
        lblQtdPatrocinadores = new javax.swing.JLabel();
        lblQtdInscricoes = new javax.swing.JLabel();
        lblInscricoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGastos = new javax.swing.JTable();
        lblGastosEvento = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IFIP Congressos //Gerenciamento Financeiro");
        setMinimumSize(new java.awt.Dimension(663, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        txtDescricaoItem.setColumns(20);
        txtDescricaoItem.setRows(5);
        jScrollPane2.setViewportView(txtDescricaoItem);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 460, 50);

        lblDescricaoItem.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblDescricaoItem.setForeground(new java.awt.Color(255, 255, 255));
        lblDescricaoItem.setText("Descrição do Item:");
        getContentPane().add(lblDescricaoItem);
        lblDescricaoItem.setBounds(20, 50, 140, 17);

        lblCustoItem.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblCustoItem.setForeground(new java.awt.Color(255, 255, 255));
        lblCustoItem.setText("Custo:");
        getContentPane().add(lblCustoItem);
        lblCustoItem.setBounds(500, 70, 50, 20);

        txtCustoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoItemActionPerformed(evt);
            }
        });
        getContentPane().add(txtCustoItem);
        txtCustoItem.setBounds(550, 70, 80, 20);

        lblAtualizar.setFont(new java.awt.Font("Eras Medium ITC", 0, 10)); // NOI18N
        lblAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblAtualizar.setText("Atualizar");
        lblAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtualizarMouseClicked(evt);
            }
        });
        getContentPane().add(lblAtualizar);
        lblAtualizar.setBounds(580, 290, 50, 13);

        imgAtualizar.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        imgAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        imgAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/atualizar32.png"))); // NOI18N
        imgAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAtualizarMouseClicked(evt);
            }
        });
        getContentPane().add(imgAtualizar);
        imgAtualizar.setBounds(580, 260, 40, 40);

        btnCadastrar.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(500, 100, 130, 20);

        lblLucro.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblLucro.setForeground(new java.awt.Color(255, 255, 255));
        lblLucro.setText("Saldo do Evento:");
        getContentPane().add(lblLucro);
        lblLucro.setBounds(330, 350, 130, 17);

        lblQtdLucro.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblQtdLucro.setForeground(new java.awt.Color(255, 255, 255));
        lblQtdLucro.setText("00");
        getContentPane().add(lblQtdLucro);
        lblQtdLucro.setBounds(480, 350, 90, 17);

        lblSaida.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblSaida.setForeground(new java.awt.Color(255, 255, 255));
        lblSaida.setText("Valor de Saída:");
        getContentPane().add(lblSaida);
        lblSaida.setBounds(20, 380, 110, 17);

        lblQtdSaida.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblQtdSaida.setForeground(new java.awt.Color(255, 255, 255));
        lblQtdSaida.setText("00");
        getContentPane().add(lblQtdSaida);
        lblQtdSaida.setBounds(170, 380, 110, 17);

        lblEntrada.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblEntrada.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrada.setText("Valor de Entrada:");
        getContentPane().add(lblEntrada);
        lblEntrada.setBounds(20, 350, 130, 17);

        lblQtdEntrada.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblQtdEntrada.setForeground(new java.awt.Color(255, 255, 255));
        lblQtdEntrada.setText("00");
        getContentPane().add(lblQtdEntrada);
        lblQtdEntrada.setBounds(170, 350, 110, 17);

        lblTitle2.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("Balanço Final");
        getContentPane().add(lblTitle2);
        lblTitle2.setBounds(20, 310, 170, 29);

        lblPatrocinadores.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblPatrocinadores.setForeground(new java.awt.Color(255, 255, 255));
        lblPatrocinadores.setText("Valor de Patrocinadores:");
        getContentPane().add(lblPatrocinadores);
        lblPatrocinadores.setBounds(310, 260, 170, 17);

        lblQtdPatrocinadores.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblQtdPatrocinadores.setForeground(new java.awt.Color(255, 255, 255));
        lblQtdPatrocinadores.setText("00");
        getContentPane().add(lblQtdPatrocinadores);
        lblQtdPatrocinadores.setBounds(490, 260, 80, 17);

        lblQtdInscricoes.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblQtdInscricoes.setForeground(new java.awt.Color(255, 255, 255));
        lblQtdInscricoes.setText("00");
        getContentPane().add(lblQtdInscricoes);
        lblQtdInscricoes.setBounds(220, 260, 80, 17);

        lblInscricoes.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblInscricoes.setForeground(new java.awt.Color(255, 255, 255));
        lblInscricoes.setText("Quantidade de Inscrições:");
        getContentPane().add(lblInscricoes);
        lblInscricoes.setBounds(20, 260, 190, 17);

        tbGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição do Item", "Valor Gasto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGastos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbGastos);
        if (tbGastos.getColumnModel().getColumnCount() > 0) {
            tbGastos.getColumnModel().getColumn(0).setResizable(false);
            tbGastos.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 610, 100);

        lblGastosEvento.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblGastosEvento.setForeground(new java.awt.Color(255, 255, 255));
        lblGastosEvento.setText("Gastos com o evento:");
        getContentPane().add(lblGastosEvento);
        lblGastosEvento.setBounds(20, 130, 170, 17);

        lblTitle.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Gerenciamento Financeiro");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(20, 10, 480, 29);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/fundo.jpg"))); // NOI18N
        imgFundo.setName("imgFundo"); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(-10, -10, 700, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    void atualizarDados(){
        //zera para nao conter lbl sem valor
        lblQtdInscricoes.setText(Double.toString(0));
        lblQtdPatrocinadores.setText(Double.toString(0));
        lblQtdEntrada.setText(Double.toString(0));
        lblQtdSaida.setText(Double.toString(0));
        lblQtdLucro.setText(Double.toString(0));
        
        Conexao cx = Conexao.getInstancia();
        
        try {
            Connection con = cx.conectar();
            Statement consulta = con.createStatement();
            
            ResultSet qtdinscricao = consulta.executeQuery("SELECT COUNT(*) AS QTD_INSCRICAO FROM PESSOA WHERE FUNCAO = 'Participante'");
            ResultSet valorpatro = consulta.executeQuery("SELECT SUM(VALORPATROCINIO) AS VALOR_TOTAL FROM PATROCINADOR");
            ResultSet valorcongresso = consulta.executeQuery("SELECT VALORINSCRICAO FROM CONGRESSO WHERE IDCONGRESSO = 1");
            ResultSet gastototal = consulta.executeQuery("SELECT SUM(VALOR) AS GASTO_TOTAL FROM GASTOS");
            
            if (qtdinscricao.next() && valorpatro.next() && valorcongresso.next() && gastototal.next()){
                lblQtdInscricoes.setText(qtdinscricao.getString("QTD_INSCRICAO"));
                
                lblQtdPatrocinadores.setText(valorpatro.getString("VALOR_TOTAL"));
                
                double qtdinscricoes = (double) (Double.valueOf(lblQtdInscricoes.getText()));
                double valorinscricao = (double) (Double.valueOf(valorcongresso.getString("VALORINSCRICAO")));
                lblQtdEntrada.setText(Double.toString(qtdinscricoes * valorinscricao));
                
                lblQtdSaida.setText(gastototal.getString("GASTO_TOTAL"));
                
                double entrada = (double) (Double.valueOf(lblQtdEntrada.getText()));
                double saida = (double) (Double.valueOf(lblQtdSaida.getText()));
                lblQtdLucro.setText(Double.toString(entrada - saida));
            }  
            
            cx.desconectar();
        } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
        }
    }
    
    void fazerBusca(){
        dtm.setNumRows(0);
        
        Conexao cx = Conexao.getInstancia();
        
        try {
            Connection con = cx.conectar();
            Statement consulta = con.createStatement();
            ResultSet resultado = consulta.executeQuery("SELECT * FROM GASTOS");
            while (resultado.next()){
                dtm.addRow(new Object[] {resultado.getString("DESCRICAO"), resultado.getInt("VALOR")});
            }
            cx.desconectar();
        } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
        }
    }
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Conexao cx = Conexao.getInstancia();
        
        //JOptionPane.showMessageDialog(null, this.getId());
        
        try {
            Connection con = cx.conectar();
            Statement query = con.createStatement();
            query.executeUpdate("INSERT INTO GASTOS "
                    + "(DESCRICAO, VALOR) "
                    + "VALUES "
                    + "('" + txtDescricaoItem.getText() + "', "
                    + "'" + txtCustoItem.getText() + "')");
            cx.desconectar();
            
            JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso!");
            
        } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtCustoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustoItemActionPerformed

    private void imgAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAtualizarMouseClicked
        // TODO add your handling code here:
        fazerBusca();
        atualizarDados();
    }//GEN-LAST:event_imgAtualizarMouseClicked

    private void lblAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtualizarMouseClicked
        // TODO add your handling code here:
        fazerBusca();
        atualizarDados();
    }//GEN-LAST:event_lblAtualizarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        fazerBusca();
        atualizarDados();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaControleFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel imgAtualizar;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAtualizar;
    private javax.swing.JLabel lblCustoItem;
    private javax.swing.JLabel lblDescricaoItem;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblGastosEvento;
    private javax.swing.JLabel lblInscricoes;
    private javax.swing.JLabel lblLucro;
    private javax.swing.JLabel lblPatrocinadores;
    private javax.swing.JLabel lblQtdEntrada;
    private javax.swing.JLabel lblQtdInscricoes;
    private javax.swing.JLabel lblQtdLucro;
    private javax.swing.JLabel lblQtdPatrocinadores;
    private javax.swing.JLabel lblQtdSaida;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTable tbGastos;
    private javax.swing.JTextField txtCustoItem;
    private javax.swing.JTextArea txtDescricaoItem;
    // End of variables declaration//GEN-END:variables
}
