/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VISAO;

import PRINCIPAL.Conexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lennon
 */
public class TelaBuscar extends javax.swing.JFrame {

    /**
     * Creates new form TelaBuscar
     */
    
    DefaultTableModel dtm = new DefaultTableModel();
    public static TelaBuscar instancia;
    
    protected TelaBuscar() {
        initComponents();
        dtm = (DefaultTableModel) tbPesquisa.getModel();
    }
    
    public static TelaBuscar getInstancia() {
        if (instancia == null)
            instancia = new TelaBuscar();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscar = new javax.swing.JLabel();
        lblImgBuscar = new javax.swing.JLabel();
        lblJanela = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesquisa = new javax.swing.JTable();
        imgFundo = new javax.swing.JLabel();

        setTitle("IFIP Congressos //Buscar");
        setMinimumSize(new java.awt.Dimension(663, 430));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lblBuscar.setFont(new java.awt.Font("Eras Medium ITC", 0, 10)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Fazer Busca");
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(lblBuscar);
        lblBuscar.setBounds(570, 40, 60, 13);

        lblImgBuscar.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblImgBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblImgBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/lupa32.png"))); // NOI18N
        lblImgBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(lblImgBuscar);
        lblImgBuscar.setBounds(580, 0, 40, 40);

        lblJanela.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblJanela.setForeground(new java.awt.Color(255, 102, 0));
        lblJanela.setText("[JANELA]");
        getContentPane().add(lblJanela);
        lblJanela.setBounds(20, 40, 500, 28);

        lblTitle.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Pesquisar");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(20, 10, 390, 29);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(340, 350, 100, 28);

        btnEnviar.setText("ENVIAR SELEÇÃO");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(470, 350, 160, 28);

        tbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPesquisa.getTableHeader().setReorderingAllowed(false);
        tbPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPesquisa);
        tbPesquisa.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbPesquisa.getColumnModel().getColumnCount() > 0) {
            tbPesquisa.getColumnModel().getColumn(0).setResizable(false);
            tbPesquisa.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 610, 240);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/fundo.jpg"))); // NOI18N
        imgFundo.setName("imgFundo"); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(-10, -10, 710, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int definirTela = 0;
    private int linha;
    private int nautor;
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); //fecha tela de busca
        
        if (this.getDefinirTela() == 1){ //Congresso
            TelaCongresso Congresso = TelaCongresso.getInstancia(); //chama instancia
            Congresso.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 2){ //Editora
            TelaEditoras Editora = TelaEditoras.getInstancia(); //chama instancia
            Editora.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 3){ //Pessoa
            TelaPessoas Pessoa = TelaPessoas.getInstancia(); //chama instancia
            Pessoa.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 4){ //Patrocinador
            TelaPatrocinadores Patrocinador = TelaPatrocinadores.getInstancia(); //chama instancia
            Patrocinador.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 5){ //Usuários
            TelaUsuarios Usuario = TelaUsuarios.getInstancia(); //chama instancia
            Usuario.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 6){ //Autores
            TelaSubmeterArtigo Autor = TelaSubmeterArtigo.getInstancia(); //chama instancia
            Autor.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 7){ //Sessao
            TelaSessoes Sessao = TelaSessoes.getInstancia(); //chama instancia
            Sessao.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 8){ //Moderador Sessao
            TelaSessoes Sessao = TelaSessoes.getInstancia(); //chama instancia
            Sessao.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 9 || this.getDefinirTela() == 10){ //Publicacao
            TelaPublicacoes Publica = TelaPublicacoes.getInstancia(); //chama instancia
            Publica.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 11){ //Julgar Artigos
            TelaJulgarArtigo Julgar = TelaJulgarArtigo.getInstancia(); //chama instancia
            Julgar.setVisible(true); //chama tela buscada
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void fazerBusca (){
        dtm.setNumRows(0);
        Conexao cx = Conexao.getInstancia();
        
        if (this.getDefinirTela() == 1){
            //CONGRESSOS
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM CONGRESSO ORDER BY NOME");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDCONGRESSO"), resultado.getString("NOME")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 2){
            //EDITORAS
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM EDITORA ORDER BY NOME");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDEDITORA"), resultado.getString("NOME")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 3){
            //PESSOAS
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM PESSOA ORDER BY NOME");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDPESSOA"), resultado.getString("NOME")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 4){
            //PATROCINADORES
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM PATROCINADOR ORDER BY NOME");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDPATROCINADOR"), resultado.getString("NOME")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 5){
            //LOGIN
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM LOGIN WHERE FUNCAO <> 'admin' ORDER BY NOME");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDLOGIN"), resultado.getString("NOME")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 6){
            //AUTORES
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM PESSOA WHERE FUNCAO = 'Autor' ORDER BY NOME");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDPESSOA"), resultado.getString("NOME")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 7){
            //SESSAO
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM SESSAO ORDER BY AREA");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDSESSAO"), resultado.getString("AREA")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 8){
            //MODERADOR
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM PESSOA WHERE FUNCAO = 'Moderador' ORDER BY NOME");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDPESSOA"), resultado.getString("NOME")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 9){
            //ARTIGOS
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM ARTIGO WHERE STATUS = 4 ORDER BY TITULO");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDARTIGO"), resultado.getString("TITULO")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 10){
            //EDITORAS
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM EDITORA");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDEDITORA"), resultado.getString("NOME")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
        if (this.getDefinirTela() == 11){
            //ARTIGOS //JULGAR
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM ARTIGO WHERE STATUS = 3 AND DATAJULGAMENTOARTIGO IS NULL");
                while (resultado.next()){
                    dtm.addRow(new Object[] {resultado.getString("IDARTIGO"), resultado.getString("TITULO")});
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
        }
    }
    
    private void lblImgBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgBuscarMouseClicked
        // TODO add your handling code here:
        fazerBusca();
    }//GEN-LAST:event_lblImgBuscarMouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        // TODO add your handling code here:
        fazerBusca();
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (this.getDefinirTela() == 1){
            this.lblJanela.setText("Buscar Congresso");
        }
        if (this.getDefinirTela() == 2 || this.getDefinirTela() == 10){
            this.lblJanela.setText("Buscar Editora");
        }
        if (this.getDefinirTela() == 3){
            this.lblJanela.setText("Buscar Pessoa");
        }
        if (this.getDefinirTela() == 4){
            this.lblJanela.setText("Buscar Patrocinador");
        }
        if (this.getDefinirTela() == 5){
            this.lblJanela.setText("Buscar Usuário");
        }
        if (this.getDefinirTela() == 6){
            this.lblJanela.setText("Buscar Autor");
        }
        if (this.getDefinirTela() == 7){
            this.lblJanela.setText("Buscar Sessão");
        }
        if (this.getDefinirTela() == 8){
            this.lblJanela.setText("Buscar Moderador");
        }
        if (this.getDefinirTela() == 9 || this.getDefinirTela() == 11){
            this.lblJanela.setText("Buscar Artigo");
        }
    }//GEN-LAST:event_formWindowActivated

    private void tbPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPesquisaMouseClicked
        // TODO add your handling code here:
        
        setLinha(Integer.parseInt((String) tbPesquisa.getValueAt(tbPesquisa.getSelectedRow(), 0)));
        //JOptionPane.showMessageDialog(null, "LINHA: " + linha);
        
    }//GEN-LAST:event_tbPesquisaMouseClicked
    
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); //fecha tela de busca
        
        if (this.getDefinirTela() == 1){ //Congresso
            TelaCongresso Congresso = TelaCongresso.getInstancia(); //chama instancia
            Congresso.setId(getLinha()); //recebe id
            Congresso.preencheTela(1); //liga flag
            Congresso.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 2){ //Editora
            TelaEditoras Editora = TelaEditoras.getInstancia(); //chama instancia
            Editora.setId(getLinha()); //recebe id
            Editora.preencheTela(1); //liga flag
            Editora.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 3){ //Pessoa
            TelaPessoas Pessoa = TelaPessoas.getInstancia(); //chama instancia
            Pessoa.setId(getLinha()); //recebe id
            Pessoa.preencheTela(1); //liga flag
            Pessoa.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 4){ //Patrocinador
            TelaPatrocinadores Patrocinador = TelaPatrocinadores.getInstancia(); //chama instancia
            Patrocinador.setId(getLinha()); //recebe id
            Patrocinador.preencheTela(1); //liga flag
            Patrocinador.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 5){ //Usuários
            TelaUsuarios Usuario = TelaUsuarios.getInstancia(); //chama instancia
            Usuario.setId(getLinha()); //recebe id
            Usuario.preencheTela(1); //liga flag
            Usuario.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 6){ //Autores
            TelaSubmeterArtigo Autor = TelaSubmeterArtigo.getInstancia(); //chama instancia
            Autor.setId(getLinha()); //recebe id
            if(this.getNautor() == 1){
                Autor.setNautor(1);
            }
            if(this.getNautor() == 2){
                Autor.setNautor(2);
            }
            if(this.getNautor() == 3){
                Autor.setNautor(3);
            }
            Autor.preencheTela(1); //liga flag
            Autor.setVisible(true);//chama tela buscada
        }
        
        if (this.getDefinirTela() == 7){ //Sessao
            TelaSessoes Sessao = TelaSessoes.getInstancia(); //chama instancia
            Sessao.setId(getLinha()); //recebe id
            Sessao.preencheTela(1); //liga flag
            Sessao.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 8){ //Moderador
            TelaSessoes Sessao = TelaSessoes.getInstancia(); //chama instancia
            Sessao.setId(getLinha()); //recebe id
            Sessao.preencheModerador(1); //liga flag
            Sessao.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 9){ //Artigo Publicacao
            TelaPublicacoes Publica = TelaPublicacoes.getInstancia(); //chama instancia
            Publica.setId(getLinha()); //recebe id
            Publica.preencheTela(1); //liga flag
            Publica.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 10){ //Editora Publicacao
            TelaPublicacoes Publica = TelaPublicacoes.getInstancia(); //chama instancia
            Publica.setId(getLinha()); //recebe id
            Publica.preencheTela(2); //liga flag
            Publica.setVisible(true); //chama tela buscada
        }
        
        if (this.getDefinirTela() == 11){ //Artigo Julgar
            TelaJulgarArtigo Julgar = TelaJulgarArtigo.getInstancia(); //chama instancia
            Julgar.setId(getLinha()); //recebe id
            Julgar.preencheTela(1); //liga flag
            Julgar.setVisible(true); //chama tela buscada
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblImgBuscar;
    private javax.swing.JLabel lblJanela;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tbPesquisa;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the definirTela
     */
    public int getDefinirTela() {
        return definirTela;
    }

    /**
     * @param definirTela the definirTela to set
     */
    public void setDefinirTela(int definirTela) {
        this.definirTela = definirTela;
    }

    /**
     * @return the linha
     */
    public int getLinha() {
        return linha;
    }

    /**
     * @param linha the linha to set
     */
    public void setLinha(int linha) {
        this.linha = linha;
    }

    /**
     * @return the nautor
     */
    public int getNautor() {
        return nautor;
    }

    /**
     * @param nautor the nautor to set
     */
    public void setNautor(int nautor) {
        this.nautor = nautor;
    }
}