/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VISAO;

import PRINCIPAL.Conexao;
import PRINCIPAL.JulgarArtigo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author lennon
 */
public class TelaJulgarArtigo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJulgarArtigo
     */
    
    private int id = 0;
    public static TelaJulgarArtigo instancia;
    
    protected TelaJulgarArtigo() {
        initComponents();
    }
    
    public static TelaJulgarArtigo getInstancia() {
        if (instancia == null)
            instancia = new TelaJulgarArtigo();
        return instancia;
    }
    
    Date data = new Date();
    java.sql.Date dataSQL = new java.sql.Date(data.getTime());
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSituacao = new javax.swing.JLabel();
        txtTituloArtigo = new javax.swing.JTextField();
        btnTituloArtigo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSubmeter = new javax.swing.JButton();
        lblAvaliacao1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAvaliacao1 = new javax.swing.JTextArea();
        lblAvaliacao2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAvaliacao2 = new javax.swing.JTextArea();
        lblAvaliacao3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAvaliacao3 = new javax.swing.JTextArea();
        lblTituloArtigo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        cbSituacao = new javax.swing.JComboBox();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IFIP Congressos //Sistema de Julgamento de Artigos");
        setMinimumSize(new java.awt.Dimension(663, 600));
        getContentPane().setLayout(null);

        lblSituacao.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblSituacao.setForeground(new java.awt.Color(255, 255, 255));
        lblSituacao.setText("Situação do Artigo:");
        getContentPane().add(lblSituacao);
        lblSituacao.setBounds(20, 480, 130, 17);

        txtTituloArtigo.setEnabled(false);
        getContentPane().add(txtTituloArtigo);
        txtTituloArtigo.setBounds(150, 70, 420, 28);

        btnTituloArtigo.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        btnTituloArtigo.setText("...");
        btnTituloArtigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTituloArtigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTituloArtigoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTituloArtigo);
        btnTituloArtigo.setBounds(580, 70, 40, 30);

        btnCancelar.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(300, 520, 120, 30);

        btnSubmeter.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnSubmeter.setText("JULGAR ARTIGO");
        btnSubmeter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSubmeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmeterActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmeter);
        btnSubmeter.setBounds(440, 520, 180, 30);

        lblAvaliacao1.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblAvaliacao1.setForeground(new java.awt.Color(255, 255, 255));
        lblAvaliacao1.setText("Avaliação 1:");
        getContentPane().add(lblAvaliacao1);
        lblAvaliacao1.setBounds(20, 110, 90, 17);

        txtAvaliacao1.setEditable(false);
        txtAvaliacao1.setColumns(20);
        txtAvaliacao1.setRows(5);
        jScrollPane1.setViewportView(txtAvaliacao1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 370, 600, 90);

        lblAvaliacao2.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblAvaliacao2.setForeground(new java.awt.Color(255, 255, 255));
        lblAvaliacao2.setText("Avaliação 2:");
        getContentPane().add(lblAvaliacao2);
        lblAvaliacao2.setBounds(20, 230, 90, 17);

        txtAvaliacao2.setEditable(false);
        txtAvaliacao2.setColumns(20);
        txtAvaliacao2.setRows(5);
        jScrollPane2.setViewportView(txtAvaliacao2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 130, 600, 90);

        lblAvaliacao3.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblAvaliacao3.setForeground(new java.awt.Color(255, 255, 255));
        lblAvaliacao3.setText("Avaliação 3:");
        getContentPane().add(lblAvaliacao3);
        lblAvaliacao3.setBounds(20, 350, 90, 17);

        txtAvaliacao3.setEditable(false);
        txtAvaliacao3.setColumns(20);
        txtAvaliacao3.setRows(5);
        jScrollPane3.setViewportView(txtAvaliacao3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 250, 600, 90);

        lblTituloArtigo.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblTituloArtigo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloArtigo.setText("Título do Artigo:");
        getContentPane().add(lblTituloArtigo);
        lblTituloArtigo.setBounds(20, 80, 110, 17);

        lblTitle.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Sistema de Julgamento de Artigos");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(20, 10, 410, 29);

        cbSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprovado", "Reprovado" }));
        getContentPane().add(cbSituacao);
        cbSituacao.setBounds(170, 470, 160, 28);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/fundo.jpg"))); // NOI18N
        imgFundo.setName("imgFundo"); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(-10, -10, 680, 820);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTituloArtigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTituloArtigoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TelaBuscar Buscar = TelaBuscar.getInstancia();
        Buscar.setDefinirTela(11);
        Buscar.setVisible(true);
    }//GEN-LAST:event_btnTituloArtigoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSubmeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmeterActionPerformed
        // TODO add your handling code here:
        Conexao cx = Conexao.getInstancia();
        
        //JOptionPane.showMessageDialog(null, this.getId());
        
        try {
            Connection con = cx.conectar();
            Statement query = con.createStatement();
            
            if (cbSituacao.getSelectedItem().equals("Aprovado")){
                query.executeUpdate("UPDATE ARTIGO SET "
                    + "STATUS = " + 4 + ", "
                    + "DATAJULGAMENTOARTIGO = '" + dataSQL + "' "
                    + "WHERE IDARTIGO = " + getId());
            } else {
                query.executeUpdate("UPDATE ARTIGO SET "
                    + "DATAJULGAMENTOARTIGO = '" + dataSQL + "' "
                    + "WHERE IDARTIGO = " + getId());
            }
            
            cx.desconectar();
            
            JOptionPane.showMessageDialog(null, "Artigo julgado com sucesso!");
            //limparDados();
            
        } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
        }
    }//GEN-LAST:event_btnSubmeterActionPerformed

    void preencheTela(int aux){
        if (aux == 1){
            
            Conexao cx = Conexao.getInstancia();
        
            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet titulo = consulta.executeQuery("SELECT TITULO FROM ARTIGO WHERE IDARTIGO = " + getId());
                ResultSet parecer = consulta.executeQuery("SELECT PARECER FROM ARTIGO AR "
                        + "JOIN AVALIACAO AV "
                        + "ON AR.IDARTIGO = AV.IDARTIGO "
                        + "WHERE AR.IDARTIGO = " + getId());
                if (titulo.next()){
                    txtTituloArtigo.setText(titulo.getString("TITULO"));
                    if (parecer.next())
                        txtAvaliacao1.setText(parecer.getString("PARECER"));
                    if (parecer.next())
                        txtAvaliacao2.setText(parecer.getString("PARECER"));
                    if (parecer.next())
                        txtAvaliacao3.setText(parecer.getString("PARECER"));
                }
                cx.desconectar();
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
            }
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJulgarArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJulgarArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJulgarArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJulgarArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJulgarArtigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSubmeter;
    private javax.swing.JButton btnTituloArtigo;
    private javax.swing.JComboBox cbSituacao;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAvaliacao1;
    private javax.swing.JLabel lblAvaliacao2;
    private javax.swing.JLabel lblAvaliacao3;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTituloArtigo;
    private javax.swing.JTextArea txtAvaliacao1;
    private javax.swing.JTextArea txtAvaliacao2;
    private javax.swing.JTextArea txtAvaliacao3;
    private javax.swing.JTextField txtTituloArtigo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }
}
