/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TELAS;

import PERS.Conexao;
import RN.PatrocinadoresRN;
import VO.BuscaVO;
import VO.PatrocinadoresVO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author lennon
 */
public class TelaPatrocinadores extends javax.swing.JFrame {

    /**
     * Creates new form TelaPatrocinadores
     */
    
    public static TelaPatrocinadores instancia;
    
    protected TelaPatrocinadores() {
        initComponents();
    }
    
    public static TelaPatrocinadores getInstancia() {
        if (instancia == null)
            instancia = new TelaPatrocinadores();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValorPatrocinio = new javax.swing.JTextField();
        lblValorPatrocinio = new javax.swing.JLabel();
        lblImgBuscar = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        lblEmailPatrocinador = new javax.swing.JLabel();
        txtEmailPatrocinador = new javax.swing.JTextField();
        txtTelefonePatrocinador = new javax.swing.JFormattedTextField();
        lblTelefonePatrocinador = new javax.swing.JLabel();
        txtEnderecoPatrocinador = new javax.swing.JTextField();
        lblEnderecoPatrocinador = new javax.swing.JLabel();
        txtNomePatrocinador = new javax.swing.JTextField();
        lblNomePatrocinador = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblCNPJPatrocinador = new javax.swing.JLabel();
        txtCNPJPatrocinador = new javax.swing.JTextField();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IFIP Congressos //Cadastro de Patrocinadores");
        setMinimumSize(new java.awt.Dimension(663, 290));
        getContentPane().setLayout(null);
        getContentPane().add(txtValorPatrocinio);
        txtValorPatrocinio.setBounds(520, 150, 100, 28);

        lblValorPatrocinio.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblValorPatrocinio.setForeground(new java.awt.Color(255, 255, 255));
        lblValorPatrocinio.setText("Valor:");
        getContentPane().add(lblValorPatrocinio);
        lblValorPatrocinio.setBounds(470, 160, 40, 17);

        lblImgBuscar.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblImgBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblImgBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/lupa32.png"))); // NOI18N
        lblImgBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(lblImgBuscar);
        lblImgBuscar.setBounds(580, 0, 40, 40);

        lblBuscar.setFont(new java.awt.Font("Eras Medium ITC", 0, 10)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar");
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(lblBuscar);
        lblBuscar.setBounds(580, 40, 40, 13);

        lblEmailPatrocinador.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblEmailPatrocinador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailPatrocinador.setText("Email:");
        getContentPane().add(lblEmailPatrocinador);
        lblEmailPatrocinador.setBounds(20, 160, 50, 17);

        txtEmailPatrocinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailPatrocinadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmailPatrocinador);
        txtEmailPatrocinador.setBounds(100, 150, 350, 28);

        try {
            txtTelefonePatrocinador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtTelefonePatrocinador);
        txtTelefonePatrocinador.setBounds(470, 70, 150, 28);

        lblTelefonePatrocinador.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblTelefonePatrocinador.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefonePatrocinador.setText("Telefone:");
        getContentPane().add(lblTelefonePatrocinador);
        lblTelefonePatrocinador.setBounds(390, 80, 70, 17);

        txtEnderecoPatrocinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoPatrocinadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtEnderecoPatrocinador);
        txtEnderecoPatrocinador.setBounds(100, 110, 360, 30);

        lblEnderecoPatrocinador.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblEnderecoPatrocinador.setForeground(new java.awt.Color(255, 255, 255));
        lblEnderecoPatrocinador.setText("Endereço:");
        getContentPane().add(lblEnderecoPatrocinador);
        lblEnderecoPatrocinador.setBounds(20, 120, 80, 20);

        txtNomePatrocinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePatrocinadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomePatrocinador);
        txtNomePatrocinador.setBounds(100, 70, 280, 28);

        lblNomePatrocinador.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblNomePatrocinador.setForeground(new java.awt.Color(255, 255, 255));
        lblNomePatrocinador.setText("Nome:");
        getContentPane().add(lblNomePatrocinador);
        lblNomePatrocinador.setBounds(20, 70, 50, 17);

        btnCancelar.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(280, 200, 100, 30);

        btnEditar.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(390, 200, 100, 30);

        btnCadastrar.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(500, 200, 120, 30);

        lblTitle.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Cadastro de Patrocinadores");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(20, 10, 480, 29);

        lblCNPJPatrocinador.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblCNPJPatrocinador.setForeground(new java.awt.Color(255, 255, 255));
        lblCNPJPatrocinador.setText("CNPJ:");
        getContentPane().add(lblCNPJPatrocinador);
        lblCNPJPatrocinador.setBounds(480, 120, 40, 17);

        txtCNPJPatrocinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNPJPatrocinadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtCNPJPatrocinador);
        txtCNPJPatrocinador.setBounds(530, 110, 90, 30);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/fundo.jpg"))); // NOI18N
        imgFundo.setName("imgFundo"); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(-10, -10, 680, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailPatrocinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailPatrocinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailPatrocinadorActionPerformed

    private void txtEnderecoPatrocinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoPatrocinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoPatrocinadorActionPerformed

    private void txtNomePatrocinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePatrocinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePatrocinadorActionPerformed

    private void txtCNPJPatrocinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNPJPatrocinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNPJPatrocinadorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lblImgBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgBuscarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
        BuscaVO bvo = BuscaVO.getInstancia();
        bvo.setDefinirTela(4);
        
        TelaBuscar telaBuscar = TelaBuscar.getInstancia();
        telaBuscar.setVisible(true);
    }//GEN-LAST:event_lblImgBuscarMouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
        BuscaVO bvo = BuscaVO.getInstancia();
        bvo.setDefinirTela(4);
        
        TelaBuscar telaBuscar = TelaBuscar.getInstancia();
        telaBuscar.setVisible(true);
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        PatrocinadoresVO pvo = PatrocinadoresVO.getInstancia();
        pvo.setNome(txtNomePatrocinador.getText());
        pvo.setCnpj(txtCNPJPatrocinador.getText());
        pvo.setEndereco(txtEnderecoPatrocinador.getText());
        pvo.setTelefone(txtTelefonePatrocinador.getText());
        pvo.setEmail(txtEmailPatrocinador.getText());
        pvo.setValor(Integer.parseInt(txtValorPatrocinio.getText()));
        
        PatrocinadoresRN prn = PatrocinadoresRN.getInstancia();
        prn.editarPatrocinador(pvo);
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        
        PatrocinadoresVO pvo = PatrocinadoresVO.getInstancia();
        pvo.setNome(txtNomePatrocinador.getText());
        pvo.setCnpj(txtCNPJPatrocinador.getText());
        pvo.setEndereco(txtEnderecoPatrocinador.getText());
        pvo.setTelefone(txtTelefonePatrocinador.getText());
        pvo.setEmail(txtEmailPatrocinador.getText());
        pvo.setValor(Integer.parseInt(txtValorPatrocinio.getText()));
        
        PatrocinadoresRN prn = PatrocinadoresRN.getInstancia();
        prn.editarPatrocinador(pvo);
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    void preencheTela(int aux){
        
        if (aux == 1){
            
            PatrocinadoresVO pvo = PatrocinadoresVO.getInstancia();
            PatrocinadoresRN prn = PatrocinadoresRN.getInstancia();
            prn.editarPatrocinador(pvo);
            
            txtNomePatrocinador.setText(pvo.getNome());
            txtCNPJPatrocinador.setText(pvo.getCnpj());
            txtEnderecoPatrocinador.setText(pvo.getEndereco());
            txtTelefonePatrocinador.setText(pvo.getTelefone());
            txtEmailPatrocinador.setText(pvo.getEmail());
            txtValorPatrocinio.setText(Double.toString(pvo.getValor()));
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPatrocinadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPatrocinadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPatrocinadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPatrocinadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPatrocinadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCNPJPatrocinador;
    private javax.swing.JLabel lblEmailPatrocinador;
    private javax.swing.JLabel lblEnderecoPatrocinador;
    private javax.swing.JLabel lblImgBuscar;
    private javax.swing.JLabel lblNomePatrocinador;
    private javax.swing.JLabel lblTelefonePatrocinador;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValorPatrocinio;
    private javax.swing.JTextField txtCNPJPatrocinador;
    private javax.swing.JTextField txtEmailPatrocinador;
    private javax.swing.JTextField txtEnderecoPatrocinador;
    private javax.swing.JTextField txtNomePatrocinador;
    private javax.swing.JFormattedTextField txtTelefonePatrocinador;
    private javax.swing.JTextField txtValorPatrocinio;
    // End of variables declaration//GEN-END:variables

}
