/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

import PERS.Conexao;
import VO.SubmeterArtigoVO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author lennon
 */
public class TelaSubmeterArtigo extends javax.swing.JFrame {

    /**
     * Creates new form TelaSubmeterArtigo
     */
    private int id = 0;
    private int nautor;
    
    Date data = new Date();
    java.sql.Date dataSQL = new java.sql.Date(data.getTime());
    
    public static TelaSubmeterArtigo instancia;
    
    protected TelaSubmeterArtigo() {
        initComponents();
    }
    
    public static TelaSubmeterArtigo getInstancia() {
        if (instancia == null)
            instancia = new TelaSubmeterArtigo();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lvlAreaArtigo = new javax.swing.JLabel();
        cbAreaArtigo = new javax.swing.JComboBox();
        lblUpar2 = new javax.swing.JLabel();
        lblUpar1 = new javax.swing.JLabel();
        imgUpar = new javax.swing.JLabel();
        txtNomeAutor3 = new javax.swing.JTextField();
        txtNomeAutor2 = new javax.swing.JTextField();
        txtNomeAutor1 = new javax.swing.JTextField();
        txtTituloArtigo = new javax.swing.JTextField();
        txtTemaArtigo = new javax.swing.JTextField();
        btnAutor3 = new javax.swing.JButton();
        btnAutor2 = new javax.swing.JButton();
        btnAutor1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSubmeter = new javax.swing.JButton();
        lblNomeAutor = new javax.swing.JLabel();
        lblTemaArtigo = new javax.swing.JLabel();
        lblTituloArtigo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IFIP Congressos //Sistema de Submissão de Artigos");
        setMinimumSize(new java.awt.Dimension(663, 390));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lvlAreaArtigo.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lvlAreaArtigo.setForeground(new java.awt.Color(255, 255, 255));
        lvlAreaArtigo.setText("Área do Artigo:");
        getContentPane().add(lvlAreaArtigo);
        lvlAreaArtigo.setBounds(20, 150, 110, 17);

        cbAreaArtigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Foundations of Computer Science", "Software:Theory and Practice", "Education", "Information Technology ", "Communication Systems", "System Modeling and Optimization", "Information Systems", "ICT and Society", "Computer Systems Technology", "Security and Privacy Protection in Information Processing Systems", "Artificial Intelligence", "Human-Computer Interaction", "Entertainment Computing" }));
        getContentPane().add(cbAreaArtigo);
        cbAreaArtigo.setBounds(140, 150, 480, 28);

        lblUpar2.setFont(new java.awt.Font("Eras Medium ITC", 0, 10)); // NOI18N
        lblUpar2.setForeground(new java.awt.Color(255, 255, 255));
        lblUpar2.setText("Arquivo");
        getContentPane().add(lblUpar2);
        lblUpar2.setBounds(580, 50, 50, 13);

        lblUpar1.setFont(new java.awt.Font("Eras Medium ITC", 0, 10)); // NOI18N
        lblUpar1.setForeground(new java.awt.Color(255, 255, 255));
        lblUpar1.setText("Upload de");
        getContentPane().add(lblUpar1);
        lblUpar1.setBounds(570, 40, 50, 13);

        imgUpar.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        imgUpar.setForeground(new java.awt.Color(255, 255, 255));
        imgUpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/upar32.png"))); // NOI18N
        getContentPane().add(imgUpar);
        imgUpar.setBounds(580, 0, 40, 40);

        txtNomeAutor3.setEnabled(false);
        getContentPane().add(txtNomeAutor3);
        txtNomeAutor3.setBounds(190, 250, 380, 28);

        txtNomeAutor2.setEnabled(false);
        getContentPane().add(txtNomeAutor2);
        txtNomeAutor2.setBounds(190, 220, 380, 28);

        txtNomeAutor1.setEnabled(false);
        getContentPane().add(txtNomeAutor1);
        txtNomeAutor1.setBounds(190, 190, 380, 28);
        getContentPane().add(txtTituloArtigo);
        txtTituloArtigo.setBounds(140, 70, 480, 28);
        getContentPane().add(txtTemaArtigo);
        txtTemaArtigo.setBounds(140, 110, 480, 28);

        btnAutor3.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        btnAutor3.setText("...");
        btnAutor3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAutor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutor3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutor3);
        btnAutor3.setBounds(580, 250, 40, 30);

        btnAutor2.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        btnAutor2.setText("...");
        btnAutor2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAutor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutor2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutor2);
        btnAutor2.setBounds(580, 220, 40, 30);

        btnAutor1.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        btnAutor1.setText("...");
        btnAutor1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutor1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutor1);
        btnAutor1.setBounds(580, 190, 40, 30);

        btnCancelar.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(310, 300, 110, 30);

        btnSubmeter.setFont(new java.awt.Font("Eras Medium ITC", 0, 12)); // NOI18N
        btnSubmeter.setText("SUBMETER ARTIGO");
        btnSubmeter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSubmeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmeterActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmeter);
        btnSubmeter.setBounds(440, 300, 180, 30);

        lblNomeAutor.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblNomeAutor.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeAutor.setText("Nome do(s) Autor(es):");
        getContentPane().add(lblNomeAutor);
        lblNomeAutor.setBounds(20, 190, 160, 17);

        lblTemaArtigo.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblTemaArtigo.setForeground(new java.awt.Color(255, 255, 255));
        lblTemaArtigo.setText("Tema do Artigo:");
        getContentPane().add(lblTemaArtigo);
        lblTemaArtigo.setBounds(20, 110, 110, 17);

        lblTituloArtigo.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        lblTituloArtigo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloArtigo.setText("Título do Artigo:");
        getContentPane().add(lblTituloArtigo);
        lblTituloArtigo.setBounds(20, 70, 110, 17);

        lblTitle.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Sistema de Submissão de Artigos");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(20, 10, 420, 29);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/fundo.jpg"))); // NOI18N
        imgFundo.setName("imgFundo"); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(-10, -10, 680, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutor1ActionPerformed
        // TODO add your handling code here:
        SubmeterArtigoVO.setTituloArtigo(txtTituloArtigo.getText());
        SubmeterArtigoVO.setTemaArtigo(txtTemaArtigo.getText());
        SubmeterArtigoVO.setNomeAutor1(txtNomeAutor1.getText());
        SubmeterArtigoVO.setNomeAutor2(txtNomeAutor2.getText());
        SubmeterArtigoVO.setNomeAutor3(txtNomeAutor3.getText());
        
        this.setVisible(false);
        TelaBuscar Buscar = TelaBuscar.getInstancia();
        Buscar.setNautor(1);
        Buscar.setDefinirTela(6);
        Buscar.setVisible(true);
    }//GEN-LAST:event_btnAutor1ActionPerformed

    private void btnAutor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutor2ActionPerformed
        // TODO add your handling code here:
        SubmeterArtigoVO.setTituloArtigo(txtTituloArtigo.getText());
        SubmeterArtigoVO.setTemaArtigo(txtTemaArtigo.getText());
        SubmeterArtigoVO.setNomeAutor1(txtNomeAutor1.getText());
        SubmeterArtigoVO.setNomeAutor2(txtNomeAutor2.getText());
        SubmeterArtigoVO.setNomeAutor3(txtNomeAutor3.getText());
        
        this.setVisible(false);
        TelaBuscar Buscar = TelaBuscar.getInstancia();
        Buscar.setNautor(2);
        Buscar.setDefinirTela(6);
        Buscar.setVisible(true);
    }//GEN-LAST:event_btnAutor2ActionPerformed

    private void btnAutor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutor3ActionPerformed
        // TODO add your handling code here:
        SubmeterArtigoVO.setTituloArtigo(txtTituloArtigo.getText());
        SubmeterArtigoVO.setTemaArtigo(txtTemaArtigo.getText());
        SubmeterArtigoVO.setNomeAutor1(txtNomeAutor1.getText());
        SubmeterArtigoVO.setNomeAutor2(txtNomeAutor2.getText());
        SubmeterArtigoVO.setNomeAutor3(txtNomeAutor3.getText());
        
        this.setVisible(false);
        TelaBuscar Buscar = TelaBuscar.getInstancia();
        Buscar.setNautor(3);
        Buscar.setDefinirTela(6);
        Buscar.setVisible(true);
    }//GEN-LAST:event_btnAutor3ActionPerformed

    void preencheTela(int aux) {
        if (aux == 1) {
            
            Conexao cx = Conexao.getInstancia();

            try {
                Connection con = cx.conectar();
                Statement consulta = con.createStatement();
                ResultSet resultado = consulta.executeQuery("SELECT * FROM PESSOA WHERE IDPESSOA = " + getId());
                    
                txtTituloArtigo.setText(SubmeterArtigoVO.getTituloArtigo());
                txtTemaArtigo.setText(SubmeterArtigoVO.getTemaArtigo());
                
                if (this.getNautor() == 1) {
                    if (resultado.next()) {
                        txtNomeAutor1.setText(resultado.getString("NOME"));
                        txtNomeAutor2.setText(SubmeterArtigoVO.getNomeAutor2());
                        txtNomeAutor3.setText(SubmeterArtigoVO.getNomeAutor3());
                    }
                }
                if (this.getNautor() == 2) {
                    if (resultado.next()) {
                        txtNomeAutor1.setText(SubmeterArtigoVO.getNomeAutor1());
                        txtNomeAutor2.setText(resultado.getString("NOME"));
                        txtNomeAutor3.setText(SubmeterArtigoVO.getNomeAutor3());
                    }
                }
                if (this.getNautor() == 3) {
                    if (resultado.next()) {
                        txtNomeAutor1.setText(SubmeterArtigoVO.getNomeAutor1());
                        txtNomeAutor2.setText(SubmeterArtigoVO.getNomeAutor2());
                        txtNomeAutor3.setText(resultado.getString("NOME"));
                    }
                }

                cx.desconectar();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERRO: " + e.getMessage());
            }

        }
    }

    private void btnSubmeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmeterActionPerformed
        // TODO add your handling code here:
        Conexao cx = Conexao.getInstancia();
        
        //JOptionPane.showMessageDialog(null, this.getId());
        
        try {
            Connection con = cx.conectar();
            Statement query = con.createStatement();
            Statement consulta = con.createStatement();
            ResultSet autor1 = consulta.executeQuery("SELECT IDPESSOA FROM PESSOA "
                    + "WHERE NOME = '" + txtNomeAutor1.getText() + "'");
            ResultSet autor2 = consulta.executeQuery("SELECT IDPESSOA FROM PESSOA "
                    + "WHERE NOME = '" + txtNomeAutor2.getText() + "'");
            ResultSet autor3 = consulta.executeQuery("SELECT IDPESSOA FROM PESSOA "
                    + "WHERE NOME = '" + txtNomeAutor3.getText() + "'");
            
            if (autor1.next()){
                int status = 0;
                if (!"".equals(txtNomeAutor2.getText())){
                    if (!"".equals(txtNomeAutor3.getText())){
                        //autor 1, 2 e 3
                        if (autor2.next()){
                            if (autor3.next()){
                                query.executeUpdate("INSERT INTO ARTIGO "
                                + "(TITULO, TEMA, AREA, AUTOR1, AUTOR2, AUTOR3, DATASUBMISSAO, STATUS) "
                                + "VALUES "
                                + "('" + txtTituloArtigo.getText() + "', "
                                + "'" + txtTemaArtigo.getText() + "', "
                                + "'" + cbAreaArtigo.getSelectedItem() + "', "
                                + "'" + autor1.getString("IDPESSOA") + "', "
                                + "'" + autor2.getString("IDPESSOA") + "', "
                                + "'" + autor3.getString("IDPESSOA") + "', "
                                + "'" + dataSQL + "', "
                                + "" + status + ")");
                            }
                        }
                    }
                    else {
                        //autor 1 e 2
                        if (autor2.next()){
                            query.executeUpdate("INSERT INTO ARTIGO "
                            + "(TITULO, TEMA, AREA, AUTOR1, AUTOR2, DATASUBMISSAO, STATUS) "
                            + "VALUES "
                            + "('" + txtTituloArtigo.getText() + "', "
                            + "'" + txtTemaArtigo.getText() + "', "
                            + "'" + cbAreaArtigo.getSelectedItem() + "', "
                            + "'" + autor1.getString("IDPESSOA") + "', "
                            + "'" + autor2.getString("IDPESSOA") + "', "
                            + "'" + dataSQL + "', "
                            + "" + status + ")");
                        }
                    }
                } else {
                    //somente autor 1
                    query.executeUpdate("INSERT INTO ARTIGO "
                    + "(TITULO, TEMA, AREA, AUTOR1, DATASUBMISSAO, STATUS) "
                    + "VALUES "
                    + "('" + txtTituloArtigo.getText() + "', "
                    + "'" + txtTemaArtigo.getText() + "', "
                    + "'" + cbAreaArtigo.getSelectedItem() + "', "
                    + "'" + autor1.getString("IDPESSOA") + "', "
                    + "'" + dataSQL + "', "
                    + "" + status + ")");
                }
            }
            
            cx.desconectar();
            
            JOptionPane.showMessageDialog(null, "Artigo submetido com sucesso!");
            //limparDados();
            
        } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "ERRO: "+ e.getMessage());
        }
    }//GEN-LAST:event_btnSubmeterActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSubmeterArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSubmeterArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSubmeterArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSubmeterArtigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSubmeterArtigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutor1;
    private javax.swing.JButton btnAutor2;
    private javax.swing.JButton btnAutor3;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSubmeter;
    private javax.swing.JComboBox cbAreaArtigo;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel imgUpar;
    private javax.swing.JLabel lblNomeAutor;
    private javax.swing.JLabel lblTemaArtigo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTituloArtigo;
    private javax.swing.JLabel lblUpar1;
    private javax.swing.JLabel lblUpar2;
    private javax.swing.JLabel lvlAreaArtigo;
    private javax.swing.JTextField txtNomeAutor1;
    private javax.swing.JTextField txtNomeAutor2;
    private javax.swing.JTextField txtNomeAutor3;
    private javax.swing.JTextField txtTemaArtigo;
    private javax.swing.JTextField txtTituloArtigo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the nautor
     */
    public int getNautor() {
        return nautor;
    }

    /**
     * @param nautor the nautor to set
     */
    public void setNautor(int nautor) {
        this.nautor = nautor;
    }
}