/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emprestimos.Telas;

/**
 *
 * @author lennonalves
 */
public class Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Servidor
     */
    public Servidor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    boolean flag = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatusServidor = new javax.swing.JLabel();
        lblImgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empréstimos entre Amigos");
        setMinimumSize(new java.awt.Dimension(316, 310));
        setName("telaServidor"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        lblStatusServidor.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        lblStatusServidor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusServidor.setText("LIGAR SERVIDOR");
        lblStatusServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatusServidorMouseClicked(evt);
            }
        });
        getContentPane().add(lblStatusServidor);
        lblStatusServidor.setBounds(70, 226, 170, 20);

        lblImgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/servidor-emprestimos.jpg"))); // NOI18N
        getContentPane().add(lblImgFundo);
        lblImgFundo.setBounds(0, 0, 320, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblStatusServidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatusServidorMouseClicked
        // TODO add your handling code here:
        if (flag == true) {
//servidor ligado
            flag = false;
            lblStatusServidor.setText("LIGAR SERVIDOR");
        } 
        else {
//servidor desligado
            flag = true;
            lblStatusServidor.setText("DESLIGAR SERVIDOR");
        }
    }//GEN-LAST:event_lblStatusServidorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImgFundo;
    private javax.swing.JLabel lblStatusServidor;
    // End of variables declaration//GEN-END:variables
}
