/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emprestimos.Telas;

import Emprestimos.RN.LoginRN;
import Emprestimos.VO.LoginVO;
import javax.swing.JOptionPane;

/**
 *
 * @author lennonalves
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginUsuario
     */
    
    public static TelaLogin instancia;
    
    protected TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public static TelaLogin getInstancia() {
        if (instancia == null)
            instancia = new TelaLogin();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        lblTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login | Empréstimos");
        setMinimumSize(new java.awt.Dimension(276, 310));
        setName("telaLogin"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        lblSenha.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(50, 170, 180, 16);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(50, 190, 180, 28);

        lblLogin.setFont(new java.awt.Font("Zegoe Light - U", 0, 14)); // NOI18N
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Seja Bem Vindo!");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(40, 90, 190, 20);

        lblUsuario.setFont(new java.awt.Font("Zegoe Light - U", 0, 16)); // NOI18N
        lblUsuario.setText("Usuário:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(50, 120, 180, 16);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(50, 140, 180, 28);

        btnEntrar.setFont(new java.awt.Font("Zegoe Light - U", 0, 14)); // NOI18N
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(50, 220, 180, 20);

        lblTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/login-emprestimos.jpg"))); // NOI18N
        getContentPane().add(lblTelaLogin);
        lblTelaLogin.setBounds(0, 0, 280, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        LoginVO lvo = LoginVO.getInstancia();
        lvo.setUser(txtUsuario.getText());
        lvo.setSenha(txtSenha.getText());
        
        LoginRN lrn = LoginRN.getInstancia();
        JOptionPane.showMessageDialog(null, lrn.autenticaLogin(lvo));
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelaLogin;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
